import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light sky blue — used for buttons & CTAs
        brand: {
          50:  "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",  // main button colour
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
          950: "#082f49",
        },
        // ── ServiceSelection design token colors (from reference/code.html) ──
        "primary":                   "#006195",
        "primary-container":         "#0d7ab9",
        "primary-fixed":             "#cde5ff",
        "primary-fixed-dim":         "#94ccff",
        "on-primary":                "#ffffff",
        "on-primary-fixed":          "#001d32",
        "on-primary-fixed-variant":  "#004b74",
        "on-primary-container":      "#fdfcff",
        "secondary":                 "#006a60",
        "secondary-container":       "#8cf5e4",
        "secondary-fixed":           "#8cf5e4",
        "secondary-fixed-dim":       "#6fd8c8",
        "on-secondary":              "#ffffff",
        "on-secondary-container":    "#007166",
        "on-secondary-fixed":        "#00201c",
        "on-secondary-fixed-variant":"#005048",
        "tertiary":                  "#735802",
        "tertiary-container":        "#8e711f",
        "tertiary-fixed":            "#ffdf96",
        "tertiary-fixed-dim":        "#e7c268",
        "on-tertiary":               "#ffffff",
        "on-tertiary-fixed":         "#251a00",
        "on-tertiary-fixed-variant": "#5a4400",
        "on-tertiary-container":     "#fffbff",
        "surface":                   "#fdfae7",
        "surface-dim":               "#dddbc8",
        "surface-bright":            "#fdfae7",
        "surface-variant":           "#e6e3d0",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f7f4e1",
        "surface-container":         "#f1eedb",
        "surface-container-high":    "#ece9d6",
        "surface-container-highest": "#e6e3d0",
        "surface-tint":              "#006399",
        "on-surface":                "#1c1c11",
        "on-surface-variant":        "#3d4947",
        "inverse-surface":           "#313124",
        "inverse-on-surface":        "#f4f1de",
        "inverse-primary":           "#94ccff",
        "background":                "#fdfae7",
        "on-background":             "#1c1c11",
        "outline":                   "#6d7a77",
        "outline-variant":           "#bcc9c6",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",

        // Coastal ocean blue — primary accent & UI chrome
        ocean: {
          50:  "#f0f7fb",
          100: "#d9ecf6",
          200: "#b0d8ec",
          300: "#79bade",
          400: "#429bce",
          500: "#1e7fb9",
          600: "#15659e",  // primary
          700: "#12507d",
          800: "#103f62",
          900: "#0d3150",
          950: "#081e33",
        },
      },
      fontFamily: {
        sans:     ["var(--font-inter)", "system-ui", "sans-serif"],
        headline: ["Manrope", "system-ui", "sans-serif"],
        body:     ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        label:    ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
